spring:
  config:
    import: optional:classpath:application-local.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/swizunotes
    username: postgres
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1800000
  refresh-expiration: 2592000000
  media-expiration: 43200000
